const sp = @import("./spinner.zig");

pub const Style = enum {
    dots,
    dots2,
    dots3,
    dots4,
    dots5,
    dots6,
    dots7,
    dots8,
    dots9,
    dots10,
    dots11,
    dots12,
    line,
    line2,
    pipe,
    simple_dots,
    simple_dots_scrolling,
    star,
    flip,
    hamburger,
    grow_vertical,
    grow_horizontal,
    balloon,
    noise,
    box_bounce,
    box_bounce2,
    triangle,
    arc,
    circle,
    square_corners,
    circle_quarters,
    circle_halves,
    toggle,
    toggle2,
    toggle3,
    toggle4,
    toggle5,
    toggle6,
    toggle7,
    toggle8,
    toggle9,
    toggle10,
    toggle11,
    toggle12,
    toggle13,
    arrow,
    arrow2,
    arrow3,
    bouncing_bar,
    bouncing_ball,
    smiley,
    monkey,
    hearts,
    clock,
    earth,
    moon,
    runner,
    pong,
    shark,
    dqpb,
    weather,
    christmas,
    grenade,
    point,
    layer,
    beta_wave,
    finger_dance,
    fist_bump,
    soccer_header,
    mindblown,
    speaker,
    orange_pulse,
    blue_pulse,
    orange_blue_pulse,
    aesthetic,

    pub fn data(style: Style) sp.Spinner {
        return switch (style) {
            .dots => sp.dots,
            .dots2 => sp.dots2,
            .dots3 => sp.dots3,
            .dots4 => sp.dots4,
            .dots5 => sp.dots5,
            .dots6 => sp.dots6,
            .dots7 => sp.dots7,
            .dots8 => sp.dots8,
            .dots9 => sp.dots9,
            .dots10 => sp.dots10,
            .dots11 => sp.dots11,
            .dots12 => sp.dots12,
            .line => sp.line,
            .line2 => sp.line2,
            .pipe => sp.pipe,
            .simple_dots => sp.simple_dots,
            .simple_dots_scrolling => sp.simple_dots_scrolling,
            .star => sp.star,
            .flip => sp.flip,
            .hamburger => sp.hamburger,
            .grow_vertical => sp.grow_vertical,
            .grow_horizontal => sp.grow_horizontal,
            .balloon => sp.balloon,
            .noise => sp.noise,
            .box_bounce => sp.box_bounce,
            .box_bounce2 => sp.box_bounce2,
            .triangle => sp.triangle,
            .arc => sp.arc,
            .circle => sp.circle,
            .square_corners => sp.square_corners,
            .circle_quarters => sp.circle_quarters,
            .circle_halves => sp.circle_halves,
            .toggle => sp.toggle,
            .toggle2 => sp.toggle2,
            .toggle3 => sp.toggle3,
            .toggle4 => sp.toggle4,
            .toggle5 => sp.toggle5,
            .toggle6 => sp.toggle6,
            .toggle7 => sp.toggle7,
            .toggle8 => sp.toggle8,
            .toggle9 => sp.toggle9,
            .toggle10 => sp.toggle10,
            .toggle11 => sp.toggle11,
            .toggle12 => sp.toggle12,
            .toggle13 => sp.toggle13,
            .arrow => sp.arrow,
            .arrow2 => sp.arrow2,
            .arrow3 => sp.arrow3,
            .bouncing_bar => sp.bouncing_bar,
            .bouncing_ball => sp.bouncing_ball,
            .smiley => sp.smiley,
            .monkey => sp.monkey,
            .hearts => sp.hearts,
            .clock => sp.clock,
            .earth => sp.earth,
            .moon => sp.moon,
            .runner => sp.runner,
            .pong => sp.pong,
            .shark => sp.shark,
            .dqpb => sp.dqpb,
            .weather => sp.weather,
            .christmas => sp.christmas,
            .grenade => sp.grenade,
            .point => sp.point,
            .layer => sp.layer,
            .beta_wave => sp.beta_wave,
            .finger_dance => sp.finger_dance,
            .fist_bump => sp.fist_bump,
            .soccer_header => sp.soccer_header,
            .mindblown => sp.mindblown,
            .speaker => sp.speaker,
            .orange_pulse => sp.orange_pulse,
            .blue_pulse => sp.blue_pulse,
            .orange_blue_pulse => sp.orange_blue_pulse,
            .aesthetic => sp.aesthetic,
        };
    }
};
